version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="$REPOSITORY_URI:$TAG"
  build:
    commands:
      - docker-compose docker-compose.yml build
      - docker tag gatsby "$IMAGE_URI"
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"${EnvironmentName}","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json




