version: 0.1
phases:
  pre_build:
    commands:
      - npm install -g gatsby-cli
      - npm install
      - echo Installing source NPM dependencies...
      
  build:
    commands:
      - echo Build started on `date`
      - gatsby build
      #- npm run build
  post_build:
    commands:
      #- gatsby serve
      - pwd
      - ls
      - aws s3 cp --recursive --acl public-read public s3://gatsby-test/
      #- aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/service-worker.js s3://test-pipeline-deploymentbucket-bekqcjpeiy5k/
      #- aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://test-pipeline-deploymentbucket-bekqcjpeiy5k/
      #- aws cloudfront create-invalidation --distribution-id E2PIQ80OOM7YQY --paths /index.html /service-worker.js
#artifacts:
# stores all files within a s3 deploy and build bucket
# cf dist will grab static files from deploy bucket  
#  files:
#    - '**/*'
#  base-directory: build
