version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - pwd 
      - ls
      - $(aws ecr get-login --no-include-email)
      - IMAGE_URI="383462605848.dkr.ecr.us-east-1.amazonaws.com/gatsby-js"

  build:
    commands:
      - ps -efl | grep -i docker
      - docker build --tag "$IMAGE_URI" -f Dockerfile .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"${staging}","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json




