
version: '3.3'
services:
  gatsby:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
     - .:/src
     - /node_modules/