
version: '3.7'
services:
  gatsby:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /gatsby-site
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
     - .:/gatsby-site
     - /gatsby-site/node_modules/